version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smart-search-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smartsearch
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - smart-search-network

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.15.1
    container_name: smart-search-dragonfly
    ports:
      - "6380:6379"
    volumes:
      - dragonfly_data:/data
    command: dragonfly --logtostderr
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - smart-search-network

  # Showcase Application
  mysql-dragonfly-showcase:
    build: 
      context: ../
      dockerfile: showcases/mysql-dragonfly/Dockerfile
    container_name: smart-search-mysql-dragonfly-showcase
    environment:
      - PORT=3003
      - DATABASE_URL=mysql://user:password@mysql:3306/smartsearch
      - CACHE_URL=redis://dragonfly:6379
      - DATA_SIZE=${DATA_SIZE:-medium}
    ports:
      - "3003:3003"
    depends_on:
      mysql:
        condition: service_healthy
      dragonfly:
        condition: service_healthy
    networks:
      - smart-search-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
  dragonfly_data:
    driver: local

networks:
  smart-search-network:
    driver: bridge