version: '3.8'

services:
  database:
    image: postgres:15
    container_name: smart-search-postgres
    environment:
      POSTGRES_DB: smartsearch
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d smartsearch"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - smart-search-network

  cache:
    image: redis/redis-stack-server:latest
    container_name: smart-search-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 60 1000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - smart-search-network

  # Showcase Application
  postgres-redis-showcase:
    build: 
      context: ../
      dockerfile: showcases/postgres-redis/Dockerfile
    container_name: smart-search-postgres-redis-showcase
    environment:
      - PORT=3002
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@database:5432/smartsearch
      - REDIS_URL=redis://cache:6379
      - DATA_SIZE=${DATA_SIZE:-medium}
      - SMART_SEARCH_CONFIG=/app/config/providers/postgres-redis-${INDUSTRY:-healthcare}.json
    volumes:
      - ../config:/app/config
    ports:
      - "3002:3002"
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - smart-search-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  smart-search-network:
    driver: bridge