# SmartSearch Configuration - MySQL + DragonflyDB Healthcare
# Optimized for healthcare data with MySQL + DragonflyDB infrastructure

database:
  type: mysql
  connection:
    host: mysql
    port: 3306
    database: smartsearch
    user: user
    password: password
    ssl: false
  pool:
    max: 15
    min: 3
    idleTimeoutMillis: 45000
    acquireTimeoutMillis: 60000
  options:
    charset: utf8mb4
    timezone: UTC
    sql_mode: STRICT_TRANS_TABLES

cache:
  type: dragonfly
  connection:
    host: dragonfly
    port: 6379
    db: 0
  options:
    connectTimeout: 8000
    lazyConnect: true
    retryDelayOnFailover: 200
    maxRetriesPerRequest: 4
    enableAutoPipelining: true

search:
  fallback: database
  tables:
    healthcare_data:
      columns:
        id: id
        title: title
        subtitle: specialty
        description: description
        category: type
        language: language
        visibility: visibility
        createdAt: date_created
      searchColumns:
        - title
        - description
        - condition_name
        - treatment
        - specialty
      type: healthcare
      searchConfig: fulltext
      weightConfig:
        title: 1.0
        condition_name: 1.0
        treatment: 0.8
        description: 0.6
        specialty: 0.4
      autoCreateIndexes: true
      indexStrategy: fulltext_innodb

circuitBreaker:
  failureThreshold: 4
  recoveryTimeout: 45000
  healthCacheTTL: 20000
  maxConsecutiveFailures: 6
  resetTimeout: 90000

cacheConfig:
  enabled: true
  defaultTTL: 400000
  maxSize: 15000
  keyPrefix: "mysql_healthcare:"
  compressionThreshold: 2048
  strategies:
    - type: database-first
      ttl: 240000
    - type: cache-first
      ttl: 480000
    - type: hybrid
      ttl: 360000

performance:
  enableMetrics: true
  logQueries: false
  slowQueryThreshold: 800
  maxConcurrentQueries: 40
  queryTimeout: 25000
  connectionTimeout: 8000

# MySQL + Healthcare optimizations
mysqlHealthcareOptimizations:
  fulltextMinWordLength: 3
  fulltextBooleanSyntax: "+ -><()~*:\"\"&|"
  innodbBufferPoolSize: "1G"
  queryCacheSize: "256M"
  medicalTermsOptimization: true
  icdCodeIndexing: true
  specialtyEnumOptimization: true